name: Upload pre-release image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - pip.Dockerfile
      - powershell.Dockerfile
      - .github/workflows/prerelease.yml
jobs:
  upload:
    name: Build and upload Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        variant:
          - ""
          - pip
          - powershell
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main # It must be current develop branch
      - name: Define Dockerfile path
        id: target_path
        run: echo "DOCKERFILE_PATH=./${{ matrix.variant && format('{0}.Dockerfile', matrix.variant) || 'Dockerfile' }}" >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        env:
          FULL_IMGNAME: ${{ vars.DOCKERHUB_USER }}/${{ vars.DOCKERHUB_IMGNAME }}
        with:
          context: .
          push: true
          tags: ${{ env.FULL_IMGNAME }}:pre${{ matrix.variant && format('-{0}', matrix.variant) || '' }}
          file: ${{ steps.target_path.outputs.DOCKERFILE_PATH }}
          build-args: TAGNAME=pre
