name: Upload stable image to Docker Hub
on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'
  workflow_dispatch:
env:
  STABLE_BRANCH: stable
jobs:
  upload:
    name: Build and upload Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        variant:
          - ""
          - pip
          - powershell
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.STABLE_BRANCH }}
      - name: Get year and month of pushing tags
        id: push_at
        run: echo "PUSHAT=$(date +'%Y%m')" >> "$GITHUB_OUTPUT"
      - name: Define Dockerfile path
        id: target_path
        run: echo "DOCKERFILE_PATH=./${{ matrix.variant && format('{0}.Dockerfile', matrix.variant) || 'Dockerfile' }}" >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        env:
          FULL_IMGNAME: ${{ vars.DOCKERHUB_USER }}/${{ vars.DOCKERHUB_IMGNAME }}
          POSTFIX_TAG: ${{ matrix.variant && format('-{0}', matrix.variant) || '' }}
        with:
          context: .
          push: true
          tags: |
            ${{ env.FULL_IMGNAME }}:${{ steps.push_at.outputs.PUSHAT }}${{ env.POSTFIX_TAG }}
            ${{ env.FULL_IMGNAME }}:latest${{ env.POSTFIX_TAG }}
          file: ${{ steps.target_path.outputs.DOCKERFILE_PATH }}
          build-args: TAGNAME=${{ steps.push_at.outputs.PUSHAT }}
