name: Release to Docker Hub
on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'
  workflow_dispatch:
env:
  IMAGE_NAME: rk0d/cs3103pico
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get year and month of pushing tags
        id: pushat
        run: echo "PUSHAT=$(date +'%Y%m')" >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: rk0d
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.pushat.outputs.PUSHAT }}
